export const units = {
  cup: ["c", "c.", "C", "cups", "Cups"],
  gallon: ["gal", "gallons"],
  ounce: ["oz", "oz.", "ounces"],
  pint: ["pt", "pts", "pt.", "pints"],
  pound: ["lb", "lb.", "lbs", "lbs.", "Lb", "Lbs", "pounds"],
  quart: ["qt", "qt.", "qts", "qts.", "quarts"],
  tablespoon: [
    ...[
      /*ENG*/ "tbs",
      "tbsp",
      "tbspn",
      "T",
      "T.",
      "tablespoons",
      "Tablespoons",
      "Tablespoon",
    ],
    ...[/*SV*/ "msk", "matsked", "matskedar", "Matsked", "Matskedar"],
  ],
  teaspoon: [
    ...[/*ENG*/ "tsp", "tspn", "t", "t.", "teaspoons"],
    ...[/*SV*/ "tsk", "tesked", "teskedar", "Tesked", "Teskedar"],
  ],
  kryddmatt: [...[/*SV*/ "krm", "kryddmått", "Kryddmått"]],
  gram: ["g", "G", "g.", "gr", "grams", "Gram"],
  hektogram: ["hg", "h", "h.", "H", "H.", "hekto", "Hekto", "Hg"],
  kilogram: ["kg", "kg.", "Kg", "Kg.", "KG", "kilo", "Kilo", "kilograms"],
  liter: ["l", "l.", "L", "L.", "Liter", "liters"],
  deciliter: ["dl", "dl.", "DL", "DL.", "Deciliter"],
  milligram: ["mg", "mg.", "Mg", "MG", "milligrams"],
  milliliter: ["ml", "ml.", "mL", "mL.", "ML", "milliliters"],
  package: [
    ...[/*ENG*/ "pkg", "pkgs"],
    ...[
      /*SV*/ "pkt",
      "pkt.",
      "paket",
      "Paket",
      "förp.",
      "förpackning",
      "Förpackning",
    ],
  ],
  box: ["boxes"],
  bag: [
    ...[/*ENG*/ "Bag", "bags", "Bags"],
    ...[/*SV*/ "påse", "Påse", "påsar", "Påsar"],
  ],
  can: [
    ...[/*ENG*/ "Can", "cans", "Cans"],
    ...[/*SV*/ "burk", "Burk", "burkar", "Burkar"],
  ],
  bundle: [...[/*ENG*/ "Bundle"], ...[/*SV*/ "knippe", "Knippe"]],
  stick: ["sticks"],
  piece: [
    ...[/*ENG*/ "pcs", "pcs."],
    ...[/*SV*/ "st", "st.", "ST", "St", "Styck", "styck"],
  ],
  pinch: [...[/*ENG*/ "pinches"], ...[/*SV*/ "nypa", "nypor", "Nypa", "Nypor"]],
  small: [...[/*ENG*/ "Small"], ...[/*SV*/ "liten", "Liten", "litet", "Litet"]],
  medium: [...[/*ENG*/ "Medium"], ...[/*SV*/ "medelstor", "Medelstor"]],
  large: [...[/*ENG*/ "Large"], ...[/*SV*/ "stor", "Stor", "stort", "Stort"]],
  clove: [...[/*ENG*/ "cloves"], ...[/*SV*/ "klyfta", "klyftor"]],
  slice: [...[/*ENG*/ "slices"], ...[/*SV*/ "skiva", "skivor"]],
} as { [key: string]: string[] };
